
package:
  name: cutouts
  version: "{{ version }}"

source:
  git_url: "https://github.com/B612-Asteroid-Institute/cutouts.git"
  git_tag: "v{{ version }}"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=45
    - setuptools_scm >=6.0
    - wheel
  run:
    - python >=3.7
    - numpy
    - backoff
    - astropy
    - pandas
    - pyvo
    - matplotlib
    - pandera
    - pydantic
  test:
    - pytest
    - pytest-cov
    - precommit


build:
  noarch: python
  script: pip install . --no-deps

test:
  imports:
    - cutouts

about:
  home: https://github.com/B612-Asteroid-Institute/cutouts
  license: BSD-3 Clause
  license_file: LICENSE.md
