name: conda - Build, Lint, and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "cutouts"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda install -c defaults -c conda-forge --file requirements.txt --yes
      - name: Install cutouts
        run: |
          pip install . --no-deps
      - name: Lint
        run: |
          pre-commit run --all-files
      - name: Test
        run: |
          pytest . --cov
